const SchoolController = require( "./controllers/SchoolController")
const SessionsController = require( "./controllers/SessionsController")
const EmployeeController = require( "./controllers/EmployeeController")
const ClassController = require( "./controllers/ClassController")
const StudentController = require( "./controllers/StudentController")
const MatterController = require( "./controllers/MatterContoller")
const ReportCardController = require( "./controllers/RepoCardController")
const FinalConcepts = require( "./controllers/FinalConcepts")
const AttendanceController = require( "./controllers/AttendanceController")
const BimonthlyController = require( "./controllers/BimonthlyController")
const GradeController = require( "./controllers/GradeController")
const IndividualFormController = require( "./controllers/IndividualFormController")
const RefreshController = require( "./controllers/RefreshController")

const auth = require ("./middlewares/auth")

const express = require('express')
const routes = express.Router()

routes.post('/register/school', SchoolController.create)
routes.post('/session/school', SessionsController.sessionSchool)
routes.post('/session/employee', SessionsController.sessionEmployee)
routes.post('/login-with-school', SessionsController.loginWithSchool)
routes.post('/refresh/employee', RefreshController.checkToken)

routes.post('/school/index', SchoolController.index)
routes.post('/index-school', SchoolController.indexSchools)

routes.use(auth)

routes.post('/register/employee/:id', EmployeeController.create)
routes.post('/register/class/:id', ClassController.create)
routes.post('/register/student/:id', StudentController.create)

routes.post('/add/student', ClassController.addStudent)
routes.post('/add/teacher', ClassController.addTeacher)

routes.post('/register/matter/:id', MatterController.create)
routes.post('/add/matter', MatterController.addMatter)
routes.post('/register/card', ReportCardController.create)

routes.post('/register/final-concepts', FinalConcepts.create)
routes.post('/get/final-concepts', FinalConcepts.GetGradeFinalConcepts)
routes.post('/get/card-final-concepts', FinalConcepts.GetFinalConcepts)
routes.post('/update/final-concepts', FinalConcepts.update)
routes.post('/final-concepts/daily', FinalConcepts.FinalConceptsDaily)

routes.post('/register/istQuarter', BimonthlyController.createI_stQuarter)
routes.post('/index/istQuarter', BimonthlyController.indexI_stQuarter)
routes.get('/details/istQuarter/:id', BimonthlyController.getI_stQuarterById)
routes.post('/update/istQuarter/:id', BimonthlyController.updateI_stQuarter)
routes.post('/register/iindQuarter', BimonthlyController.createII_ndQuarter)
routes.post('/index/iindQuarter', BimonthlyController.indexII_ndQuarter)
routes.get('/details/iindQuarter/:id', BimonthlyController.getII_ndQuarterById)
routes.post('/update/iindQuarter/:id', BimonthlyController.updateII_ndQuarter)
routes.post('/register/iii_rdQuarter', BimonthlyController.createIII_rdQuarter)
routes.post('/index/iii_rdQuarter', BimonthlyController.indexIII_rdQuarter)
routes.get('/details/iiirdQuarter/:id', BimonthlyController.getIII_rdQuarterById)
routes.post('/update/iiirdQuarter/:id', BimonthlyController.updateIII_rdQuarter)
routes.post('/register/iv_thQuarter', BimonthlyController.createIV_thQuarter)
routes.post('/index/iv_thQuarter', BimonthlyController.indexIV_thQuarter)
routes.get('/details/ivthQuarter/:id', BimonthlyController.getIV_thQuarterById)
routes.post('/update/ivthQuarter/:id', BimonthlyController.updateIV_thQuarter)
routes.post('/register/v_thQuarter', BimonthlyController.createV_thQuarter)
routes.post('/index/v_thQuarter', BimonthlyController.indexV_thQuarter)
routes.get('/details/vthQuarter/:id', BimonthlyController.getV_thQuarterById)
routes.post('/update/vthQuarter/:id', BimonthlyController.updateV_thQuarter)
routes.post('/register/vi_thQuarter', BimonthlyController.createVI_thQuarter)
routes.post('/index/vi_thQuarter', BimonthlyController.indexVI_thQuarter)
routes.get('/details/vithQuarter/:id', BimonthlyController.getVI_thQuarterById)
routes.post('/update/vithQuarter/:id', BimonthlyController.updateVI_thQuarter)

routes.post('/register/grade', GradeController.createGrade)
routes.post('/update/grade', GradeController.update)

routes.post('/index/gradei', GradeController.indexIstQuarter)
routes.post('/index/gradeii', GradeController.indexIIndQuarter)
routes.post('/index/gradeiii', GradeController.indexIIIrdQuarter)
routes.post('/index/gradeiv', GradeController.indexIVthQuarter)
routes.post('/index/gradev', GradeController.indexVthQuarter)
routes.post('/index/gradevi', GradeController.indexVIthQuarter)
routes.post('/get-grade', GradeController.GetGrade)
routes.post('/grade-daily', GradeController.IndexGradeDaily)

/*routes.post('/card/I_st_quarter', ReportCardController.I_st_quarter)
routes.post('/card/II_nd_quarter', ReportCardController.II_nd_quarter)
routes.post('/card/III_rd_quarter', ReportCardController.III_rd_quarter)
routes.post('/card/IV_th_quarter', ReportCardController.IV_th_quarter)*/

routes.post('/employee', EmployeeController.index)
routes.get('/employee-details/:id', EmployeeController. getEmployeeById)
routes.post('/employee-update/:id', EmployeeController.updateEmployee)
routes.post('/record-class-taught', EmployeeController.RecordClassTaught)
routes.post('/index-record-class', EmployeeController.indexRecordClassTaught)
routes.post('/update-record-class', EmployeeController.updateRecordClassTaught)
routes.post('/record-class-daily', EmployeeController.RecordClassTaughtDaily)
routes.get('/check-employee/:cpf', EmployeeController.EmpExist)

routes.get('/student-details/:id', StudentController. getStudentById)
routes.post('/student-update/:id', StudentController.updateStudent)
routes.get('/class-details/:id', ClassController.getclassById)
routes.post('/class-update/:id', ClassController.updateClass)
routes.post('/student', StudentController.index)
routes.post('/class', ClassController.index)
routes.post('/matter', MatterController.index)
routes.get('/getMatter/:id', MatterController.getMatter)

routes.post('/student/info/:id', StudentController.InfoIndex)
routes.post('/employee/info/:id', EmployeeController.InfoIndex)
routes.post('/class/info/:id', ClassController.InfoIndex)

routes.post('/myclass', EmployeeController.MyClassIndex)

routes.post('/attendance', AttendanceController.createAttendance)
routes.post('/attendance/index', StudentController.AttendanceIndex)
routes.post('/search/frequency', AttendanceController.index)
routes.post('/update/frequency', AttendanceController.update)
routes.post('/attendance-bimonthly', AttendanceController.AttendanceBimonthly)
routes.post('/attendance-final-concepts', AttendanceController.AttendanceFinalConcepts)
routes.post('/Attendance-by-teacher-class', AttendanceController.AttendanceByTeacherAndClass)

routes.post('/destroy-employee/:id', EmployeeController.destroy)
routes.post('/destroy-student/:id', StudentController.destroy)
routes.post('/remove/student', ClassController.removeStudent)
routes.post('/remove/teacher', ClassController.removeTeacher)
routes.post('/remove/matter', MatterController.removeMatter)

routes.post('/create-individual-form', IndividualFormController.createIndividualForm)
routes.post('/index-individual-form', IndividualFormController.IndexIndividualForm)
routes.get('/get-individual-form/:id', IndividualFormController.GetIndividualForm)
routes.post('/form-edit', IndividualFormController.update)

routes.post('/delete/matter', MatterController.deleteMatter)

module.exports = routes